name: Deploy docs

on:
  release:
    types: [created]

concurrency:
  group: "deploy-docs"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: pnpm i
      - run: pnpm build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./packages/doc/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
