name: publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 安装 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # 安装 Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm i -f
      - run: pnpm build
      - run: npm config set //registry.npmjs.org/:_authToken  $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: pnpm publish -r --no-git-checks --registry=$NPM_REGISTRY --access public --dry-run
